DROP TABLE AMIGOSECRETO CASCADE CONSTRAINTS;
DROP TABLE LISTAPRESENTE CASCADE CONSTRAINTS;
DROP TABLE PRESENTE CASCADE CONSTRAINTS;
DROP TABLE AMIGO CASCADE CONSTRAINTS;

CREATE TABLE AMIGO (
    AID        INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    ANOME      VARCHAR2(100) NOT NULL,
    SEXO       CHAR(1),
    IDADE      INTEGER 
);

CREATE TABLE PRESENTE (
    PID          INTEGER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    PDESCRICAO   VARCHAR2(200) NOT NULL,
    PVALOR       NUMBER(10,2)
);

CREATE TABLE LISTAPRESENTE (
    AID         INTEGER NOT NULL,
    PID         INTEGER NOT NULL,
    PREFERENCIA INTEGER,

    CONSTRAINT PK_LISTAPRESENTE PRIMARY KEY (AID, PID),
    CONSTRAINT FK_LISTAPRESENTE_AMIGO FOREIGN KEY (AID)
        REFERENCES AMIGO (AID),
    CONSTRAINT FK_LISTAPRESENTE_PRESENTE FOREIGN KEY (PID)
        REFERENCES PRESENTE (PID)
);

CREATE TABLE AMIGOSECRETO (
    AID           INTEGER NOT NULL,
    AID_AMIGO     INTEGER NOT NULL,
    PID_RECEBIDO  INTEGER NOT NULL,

    CONSTRAINT PK_AMIGOSECRETO PRIMARY KEY (AID),

    CONSTRAINT FK_AMIGOSECRETO_ORIGEM FOREIGN KEY (AID)
        REFERENCES AMIGO (AID),

    CONSTRAINT FK_AMIGOSECRETO_DEST FOREIGN KEY (AID_AMIGO)
        REFERENCES AMIGO (AID),

    CONSTRAINT FK_AMIGOSECRETO_PRESENTE FOREIGN KEY (PID_RECEBIDO)
        REFERENCES PRESENTE (PID)
);
