DROP TABLE HTL_RESERVA_SERVICO;
DROP TABLE HTL_RESERVA_STATUS_HIST;
DROP TABLE HTL_RESERVA;
DROP TABLE HTL_RESERVA_STATUS;
DROP TABLE HTL_SERVICO;
DROP TABLE HTL_QUARTO;
DROP TABLE HTL_HOSPEDE;
DROP TABLE HTL_FUNCIONARIO_FUNCAO;
DROP TABLE HTL_FUNCAO;
DROP TABLE HTL_FUNCIONARIO;

-- =====================
-- Tabela: HTL_FUNCIONARIO
-- =====================
CREATE TABLE HTL_FUNCIONARIO (
  FUNCIONARIO_ID   INTEGER GENERATED ALWAYS AS IDENTITY,
  NOME             VARCHAR2(150)    NOT NULL,
  EMAIL            VARCHAR2(150)    NOT NULL,
  SENHA            VARCHAR2(255)    NOT NULL,
  ATIVO            NUMBER(1)        DEFAULT 1 NOT NULL,
  CONSTRAINT PK_HTL_FUNCIONARIO PRIMARY KEY (FUNCIONARIO_ID),
  CONSTRAINT CK_HTL_FUNCIONARIO_ATIVO CHECK (ATIVO IN (0,1))
);

-- =====================
-- Tabela: HTL_FUNCAO
-- =====================
CREATE TABLE HTL_FUNCAO (
  FUNCAO_ID INTEGER GENERATED ALWAYS AS IDENTITY,
  NAME      VARCHAR2(80)  NOT NULL,
  CONSTRAINT PK_HTL_FUNCAO PRIMARY KEY (FUNCAO_ID)
);

-- =====================
-- Tabela: HTL_FUNCIONARIO_FUNCAO (tabela de junção)
-- =====================
CREATE TABLE HTL_FUNCIONARIO_FUNCAO (
  FUNCIONARIO_ID INTEGER NOT NULL,
  FUNCAO_ID      INTEGER NOT NULL,
  CONSTRAINT PK_HTL_FUNCIONARIO_FUNCAO PRIMARY KEY (FUNCIONARIO_ID, FUNCAO_ID),
  CONSTRAINT FK_HTL_FF_FUNCIONARIO FOREIGN KEY (FUNCIONARIO_ID)
    REFERENCES HTL_FUNCIONARIO (FUNCIONARIO_ID),
  CONSTRAINT FK_HTL_FF_FUNCAO FOREIGN KEY (FUNCAO_ID)
    REFERENCES HTL_FUNCAO (FUNCAO_ID)
);

-- =====================
-- Tabela: HTL_HOSPEDE
-- =====================
CREATE TABLE HTL_HOSPEDE (
  HOSPEDE_ID     INTEGER GENERATED ALWAYS AS IDENTITY,
  CRIADO_POR     INTEGER        NOT NULL,
  NOME           VARCHAR2(150)  NOT NULL,
  CPF            VARCHAR2(14)   NOT NULL,
  RG             VARCHAR2(20)   NULL,
  SEXO           VARCHAR2(10)   NOT NULL,
  NASCIMENTO     DATE           NOT NULL,
  EMAIL          VARCHAR2(150)  NULL,
  TELEFONE       VARCHAR2(30)   NULL,
  CRIADO_EM      TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
  ATUALIZADO_EM  TIMESTAMP(6)   NULL,
  CONSTRAINT PK_HTL_HOSPEDE PRIMARY KEY (HOSPEDE_ID),
  CONSTRAINT CK_HTL_HOSPEDE_SEXO CHECK (SEXO IN ('MASCULINO','FEMININO')),
  CONSTRAINT FK_HTL_HOSPEDE_CRIADO_POR FOREIGN KEY (CRIADO_POR)
    REFERENCES HTL_FUNCIONARIO (FUNCIONARIO_ID)
);

-- =====================
-- Tabela: HTL_QUARTO
-- =====================
CREATE TABLE HTL_QUARTO (
  QUARTO_ID     INTEGER GENERATED ALWAYS AS IDENTITY,
  IDENTIFICADOR VARCHAR2(30)   NOT NULL,
  TIPO          VARCHAR2(30)   NOT NULL,
  VALOR_DIARIA  NUMBER(10,2)   NOT NULL,
  INATIVO       NUMBER(1)      DEFAULT 0 NOT NULL,
  CONSTRAINT PK_HTL_QUARTO PRIMARY KEY (QUARTO_ID),
  CONSTRAINT CK_HTL_QUARTO_INATIVO CHECK (INATIVO IN (0,1))
);

-- =====================
-- Tabela: HTL_SERVICO
-- =====================
CREATE TABLE HTL_SERVICO (
  SERVICO_ID   INTEGER GENERATED ALWAYS AS IDENTITY,
  NOME         VARCHAR2(100)   NOT NULL,
  DESCRICAO    VARCHAR2(4000)  NULL,
  VALOR        NUMBER(10,2)    NOT NULL,
  CRIADO_EM    TIMESTAMP(6)    DEFAULT SYSTIMESTAMP NOT NULL,
  ATUALIZADO_EM TIMESTAMP(6)   NULL,
  CONSTRAINT PK_HTL_SERVICO PRIMARY KEY (SERVICO_ID)
);

-- =====================
-- Tabela: HTL_RESERVA_STATUS
-- =====================
CREATE TABLE HTL_RESERVA_STATUS (
  RESERVA_STATUS_ID INTEGER GENERATED ALWAYS AS IDENTITY,
  STATUS            VARCHAR2(30)  NOT NULL,
  CONSTRAINT PK_HTL_RESERVA_STATUS PRIMARY KEY (RESERVA_STATUS_ID),
  CONSTRAINT CK_HTL_RESERVA_STATUS CHECK (STATUS IN ('AGUARDANDO CHECK-IN','OCUPADO','CANCELADO','FINALIZADO'))
);

-- =====================
-- Tabela: HTL_RESERVA
-- =====================
CREATE TABLE HTL_RESERVA (
  RESERVA_ID         INTEGER GENERATED ALWAYS AS IDENTITY,
  QUARTO_ID          INTEGER        NOT NULL,
  HOSPEDE_ID         INTEGER        NOT NULL,
  CRIADO_POR         INTEGER        NOT NULL,
  RESERVA_STATUS_ID  INTEGER        NOT NULL,
  VALOR_CONTRATADO   NUMBER(10,2)   NOT NULL,
  DATA_INICIO        TIMESTAMP(6)   NOT NULL,
  DATA_FIM           TIMESTAMP(6)   NOT NULL,
  CHECK_IN           TIMESTAMP(6)   NULL,
  CHECK_OUT          TIMESTAMP(6)   NULL,
  CRIADO_EM          TIMESTAMP(6)   DEFAULT SYSTIMESTAMP NOT NULL,
  ATUALIZADO_EM      TIMESTAMP(6)   NULL,
  CONSTRAINT PK_HTL_RESERVA PRIMARY KEY (RESERVA_ID),
  CONSTRAINT FK_HTL_RESERVA_QUARTO FOREIGN KEY (QUARTO_ID)
    REFERENCES HTL_QUARTO (QUARTO_ID),
  CONSTRAINT FK_HTL_RESERVA_HOSPEDE FOREIGN KEY (HOSPEDE_ID)
    REFERENCES HTL_HOSPEDE (HOSPEDE_ID),
  CONSTRAINT FK_HTL_RESERVA_FUNCIONARIO FOREIGN KEY (CRIADO_POR)
    REFERENCES HTL_FUNCIONARIO (FUNCIONARIO_ID),
  CONSTRAINT FK_HTL_RESERVA_STATUS FOREIGN KEY (RESERVA_STATUS_ID)
    REFERENCES HTL_RESERVA_STATUS (RESERVA_STATUS_ID)
);

-- =====================
-- Tabela: HTL_RESERVA_STATUS_HIST
-- =====================
CREATE TABLE HTL_RESERVA_STATUS_HIST (
  STATUS_HISTORICO_ID INTEGER GENERATED ALWAYS AS IDENTITY,
  RESERVA_STATUS_ID   INTEGER        NOT NULL,
  RESERVA_ID          INTEGER        NOT NULL,
  STATUS_EM           TIMESTAMP(6)   NOT NULL,
  CONSTRAINT PK_HTL_RESERVA_STATUS_HIST PRIMARY KEY (STATUS_HISTORICO_ID),
  CONSTRAINT FK_HTL_RSH_STATUS FOREIGN KEY (RESERVA_STATUS_ID)
    REFERENCES HTL_RESERVA_STATUS (RESERVA_STATUS_ID),
  CONSTRAINT FK_HTL_RSH_RESERVA FOREIGN KEY (RESERVA_ID)
    REFERENCES HTL_RESERVA (RESERVA_ID)
);

-- =====================
-- Tabela: HTL_RESERVA_SERVICO
-- =====================
CREATE TABLE HTL_RESERVA_SERVICO (
  SERVICO_ID   INTEGER        NOT NULL,
  RESERVA_ID   INTEGER        NOT NULL,
  CONCLUIDO_EM DATE           NULL,
  VALOR        NUMBER(10,2)   NOT NULL,
  CONSTRAINT PK_HTL_RESERVA_SERVICO PRIMARY KEY (SERVICO_ID, RESERVA_ID),
  CONSTRAINT FK_HTL_RS_SERVICO FOREIGN KEY (SERVICO_ID)
    REFERENCES HTL_SERVICO (SERVICO_ID),
  CONSTRAINT FK_HTL_RS_RESERVA FOREIGN KEY (RESERVA_ID)
    REFERENCES HTL_RESERVA (RESERVA_ID)
);

-- ============================================================
-- Fim do DDL 
-- ============================================================
