INSERT INTO AMIGO (ANOME, SEXO, IDADE) VALUES ('JOAO', 'M', 25);
INSERT INTO AMIGO (ANOME, SEXO, IDADE) VALUES ('MARIA', 'F', 22);
INSERT INTO AMIGO (ANOME, SEXO, IDADE) VALUES ('CARLOS', 'M', 30);
INSERT INTO AMIGO (ANOME, SEXO, IDADE) VALUES ('ANA', 'F', 28);

INSERT INTO PRESENTE (PDESCRICAO, PVALOR) VALUES ('CAIXA DE CHOCOLATES', 35.90);
INSERT INTO PRESENTE (PDESCRICAO, PVALOR) VALUES ('CAMISETA PERSONALIZADA', 59.90);
INSERT INTO PRESENTE (PDESCRICAO, PVALOR) VALUES ('LIVRO DE FICCAO', 42.00);
INSERT INTO PRESENTE (PDESCRICAO, PVALOR) VALUES ('FONE DE OUVIDO', 79.90);

-- JOAO
INSERT INTO LISTAPRESENTE (AID, PID, PREFERENCIA) VALUES (1, 1, 5);
INSERT INTO LISTAPRESENTE (AID, PID, PREFERENCIA) VALUES (1, 2, 4);

-- MARIA
INSERT INTO LISTAPRESENTE (AID, PID, PREFERENCIA) VALUES (2, 2, 5);
INSERT INTO LISTAPRESENTE (AID, PID, PREFERENCIA) VALUES (2, 4, 4);

-- CARLOS
INSERT INTO LISTAPRESENTE (AID, PID, PREFERENCIA) VALUES (3, 3, 5);

-- ANA
INSERT INTO LISTAPRESENTE (AID, PID, PREFERENCIA) VALUES (4, 1, 4);
INSERT INTO LISTAPRESENTE (AID, PID, PREFERENCIA) VALUES (4, 3, 5);

INSERT INTO AMIGOSECRETO (AID, AID_AMIGO, PID_RECEBIDO) VALUES (1, 2, 2);
INSERT INTO AMIGOSECRETO (AID, AID_AMIGO, PID_RECEBIDO) VALUES (2, 3, 4);
INSERT INTO AMIGOSECRETO (AID, AID_AMIGO, PID_RECEBIDO) VALUES (3, 4, 3);
INSERT INTO AMIGOSECRETO (AID, AID_AMIGO, PID_RECEBIDO) VALUES (4, 1, 1);
