--------------------------------------------------------------------------------
-- FUNÇÕES
--------------------------------------------------------------------------------
INSERT INTO HTL_FUNCAO (NAME) VALUES ('Gerente');
INSERT INTO HTL_FUNCAO (NAME) VALUES ('Recepcionista');
INSERT INTO HTL_FUNCAO (NAME) VALUES ('Camareira');
INSERT INTO HTL_FUNCAO (NAME) VALUES ('Manutenção');

--------------------------------------------------------------------------------
-- FUNCIONÁRIOS
--------------------------------------------------------------------------------
INSERT INTO HTL_FUNCIONARIO (NOME, EMAIL, SENHA, ATIVO) VALUES
  ('Maria Souza', 'maria.souza@hotel.com', 'hash_senha', 1);
INSERT INTO HTL_FUNCIONARIO (NOME, EMAIL, SENHA, ATIVO) VALUES
  ('João Pereira', 'joao.pereira@hotel.com', 'hash_senha', 1);
INSERT INTO HTL_FUNCIONARIO (NOME, EMAIL, SENHA, ATIVO) VALUES
  ('Ana Lima', 'ana.lima@hotel.com', 'hash_senha', 1);
INSERT INTO HTL_FUNCIONARIO (NOME, EMAIL, SENHA, ATIVO) VALUES
  ('Carla Nunes', 'carla.nunes@hotel.com', 'hash_senha', 1);
INSERT INTO HTL_FUNCIONARIO (NOME, EMAIL, SENHA, ATIVO) VALUES
  ('Paulo Santos', 'paulo.santos@hotel.com', 'hash_senha', 1);

--------------------------------------------------------------------------------
-- FUNCIONÁRIO x FUNÇÃO
--------------------------------------------------------------------------------
-- Maria (Gerente)
INSERT INTO HTL_FUNCIONARIO_FUNCAO (FUNCIONARIO_ID, FUNCAO_ID)
SELECT f.FUNCIONARIO_ID, fu.FUNCAO_ID
FROM HTL_FUNCIONARIO f, HTL_FUNCAO fu
WHERE f.EMAIL = 'maria.souza@hotel.com' AND fu.NAME = 'Gerente';

-- João (Recepcionista)
INSERT INTO HTL_FUNCIONARIO_FUNCAO (FUNCIONARIO_ID, FUNCAO_ID)
SELECT f.FUNCIONARIO_ID, fu.FUNCAO_ID
FROM HTL_FUNCIONARIO f, HTL_FUNCAO fu
WHERE f.EMAIL = 'joao.pereira@hotel.com' AND fu.NAME = 'Recepcionista';

-- Ana (Recepcionista)
INSERT INTO HTL_FUNCIONARIO_FUNCAO (FUNCIONARIO_ID, FUNCAO_ID)
SELECT f.FUNCIONARIO_ID, fu.FUNCAO_ID
FROM HTL_FUNCIONARIO f, HTL_FUNCAO fu
WHERE f.EMAIL = 'ana.lima@hotel.com' AND fu.NAME = 'Recepcionista';

-- Carla (Camareira)
INSERT INTO HTL_FUNCIONARIO_FUNCAO (FUNCIONARIO_ID, FUNCAO_ID)
SELECT f.FUNCIONARIO_ID, fu.FUNCAO_ID
FROM HTL_FUNCIONARIO f, HTL_FUNCAO fu
WHERE f.EMAIL = 'carla.nunes@hotel.com' AND fu.NAME = 'Camareira';

-- Paulo (Manutenção)
INSERT INTO HTL_FUNCIONARIO_FUNCAO (FUNCIONARIO_ID, FUNCAO_ID)
SELECT f.FUNCIONARIO_ID, fu.FUNCAO_ID
FROM HTL_FUNCIONARIO f, HTL_FUNCAO fu
WHERE f.EMAIL = 'paulo.santos@hotel.com' AND fu.NAME = 'Manutenção';

--------------------------------------------------------------------------------
-- HÓSPEDES (CRIADO_POR referencia funcionário via e-mail)
--------------------------------------------------------------------------------
INSERT INTO HTL_HOSPEDE (CRIADO_POR, NOME, CPF, RG, SEXO, NASCIMENTO, EMAIL, TELEFONE)
SELECT f.FUNCIONARIO_ID, 'Bruno Almeida', '111.222.333-44', 'MG-12.345.678', 'MASCULINO',
       DATE '1990-03-12', 'bruno.almeida@email.com', '(31) 98888-1111'
FROM HTL_FUNCIONARIO f WHERE f.EMAIL = 'joao.pereira@hotel.com';

INSERT INTO HTL_HOSPEDE (CRIADO_POR, NOME, CPF, RG, SEXO, NASCIMENTO, EMAIL, TELEFONE)
SELECT f.FUNCIONARIO_ID, 'Fernanda Costa', '222.333.444-55', 'SP-98.765.432', 'FEMININO',
       DATE '1988-07-25', 'fernanda.costa@email.com', '(11) 97777-2222'
FROM HTL_FUNCIONARIO f WHERE f.EMAIL = 'maria.souza@hotel.com';

INSERT INTO HTL_HOSPEDE (CRIADO_POR, NOME, CPF, RG, SEXO, NASCIMENTO, EMAIL, TELEFONE)
SELECT f.FUNCIONARIO_ID, 'Pedro Rocha', '333.444.555-66', 'RJ-11.222.333', 'MASCULINO',
       DATE '1995-01-09', 'pedro.rocha@email.com', '(21) 96666-3333'
FROM HTL_FUNCIONARIO f WHERE f.EMAIL = 'ana.lima@hotel.com';

INSERT INTO HTL_HOSPEDE (CRIADO_POR, NOME, CPF, RG, SEXO, NASCIMENTO, EMAIL, TELEFONE)
SELECT f.FUNCIONARIO_ID, 'Luiza Mendes', '444.555.666-77', 'BA-44.555.666', 'FEMININO',
       DATE '1992-11-03', 'luiza.mendes@email.com', '(71) 95555-4444'
FROM HTL_FUNCIONARIO f WHERE f.EMAIL = 'joao.pereira@hotel.com';

INSERT INTO HTL_HOSPEDE (CRIADO_POR, NOME, CPF, RG, SEXO, NASCIMENTO, EMAIL, TELEFONE)
SELECT f.FUNCIONARIO_ID, 'Rafael Dias', '555.666.777-88', 'PR-22.333.444', 'MASCULINO',
       DATE '1986-05-30', 'rafael.dias@email.com', '(41) 94444-5555'
FROM HTL_FUNCIONARIO f WHERE f.EMAIL = 'maria.souza@hotel.com';

INSERT INTO HTL_HOSPEDE (CRIADO_POR, NOME, CPF, RG, SEXO, NASCIMENTO, EMAIL, TELEFONE)
SELECT f.FUNCIONARIO_ID, 'Camila Brito', '666.777.888-99', 'SC-55.666.777', 'FEMININO',
       DATE '1998-02-17', 'camila.brito@email.com', '(48) 93333-6666'
FROM HTL_FUNCIONARIO f WHERE f.EMAIL = 'ana.lima@hotel.com';

--------------------------------------------------------------------------------
-- QUARTOS
--------------------------------------------------------------------------------
INSERT INTO HTL_QUARTO (IDENTIFICADOR, TIPO, VALOR_DIARIA, INATIVO) VALUES ('101', 'STANDARD', 220.00, 0);
INSERT INTO HTL_QUARTO (IDENTIFICADOR, TIPO, VALOR_DIARIA, INATIVO) VALUES ('102', 'STANDARD', 220.00, 0);
INSERT INTO HTL_QUARTO (IDENTIFICADOR, TIPO, VALOR_DIARIA, INATIVO) VALUES ('201', 'LUXO',     350.00, 0);
INSERT INTO HTL_QUARTO (IDENTIFICADOR, TIPO, VALOR_DIARIA, INATIVO) VALUES ('202', 'LUXO',     350.00, 0);
INSERT INTO HTL_QUARTO (IDENTIFICADOR, TIPO, VALOR_DIARIA, INATIVO) VALUES ('301', 'SUITE',    500.00, 0);
INSERT INTO HTL_QUARTO (IDENTIFICADOR, TIPO, VALOR_DIARIA, INATIVO) VALUES ('401', 'FAMILIA',  400.00, 0);
INSERT INTO HTL_QUARTO (IDENTIFICADOR, TIPO, VALOR_DIARIA, INATIVO) VALUES ('402', 'FAMILIA',  400.00, 0);
INSERT INTO HTL_QUARTO (IDENTIFICADOR, TIPO, VALOR_DIARIA, INATIVO) VALUES ('501', 'SUITE MASTER', 800.00, 0);
INSERT INTO HTL_QUARTO (IDENTIFICADOR, TIPO, VALOR_DIARIA, INATIVO) VALUES ('502', 'SUITE MASTER', 800.00, 1);

--------------------------------------------------------------------------------
-- SERVIÇOS
--------------------------------------------------------------------------------
INSERT INTO HTL_SERVICO (NOME, DESCRICAO, VALOR) VALUES ('Café da manhã', 'Buffet continental', 35.00);
INSERT INTO HTL_SERVICO (NOME, DESCRICAO, VALOR) VALUES ('Almoço',         'Menu executivo',    65.00);
INSERT INTO HTL_SERVICO (NOME, DESCRICAO, VALOR) VALUES ('Jantar',         'À la carte',        70.00);
INSERT INTO HTL_SERVICO (NOME, DESCRICAO, VALOR) VALUES ('Lavanderia',     'Lavagem padrão',    25.00);
INSERT INTO HTL_SERVICO (NOME, DESCRICAO, VALOR) VALUES ('Spa',            'Massagem relax',   180.00);
INSERT INTO HTL_SERVICO (NOME, DESCRICAO, VALOR) VALUES ('Translado',      'Aeroporto ↔ Hotel',120.00);
INSERT INTO HTL_SERVICO (NOME, DESCRICAO, VALOR) VALUES ('Serviço de Quarto', 'Pedidos no quarto', 40.00);

--------------------------------------------------------------------------------
-- STATUS DE RESERVA
--------------------------------------------------------------------------------
INSERT INTO HTL_RESERVA_STATUS (STATUS) VALUES ('AGUARDANDO CHECK-IN');
INSERT INTO HTL_RESERVA_STATUS (STATUS) VALUES ('OCUPADO');
INSERT INTO HTL_RESERVA_STATUS (STATUS) VALUES ('CANCELADO');
INSERT INTO HTL_RESERVA_STATUS (STATUS) VALUES ('FINALIZADO');

--------------------------------------------------------------------------------
-- RESERVAS (datas em 2025-09, coerentes com timezone local mas sem TZ na coluna)
--------------------------------------------------------------------------------
-- 1) Bruno no 101 (FINALIZADO) 15–17/09
INSERT INTO HTL_RESERVA (
  QUARTO_ID, HOSPEDE_ID, CRIADO_POR, RESERVA_STATUS_ID,
  VALOR_CONTRATADO, DATA_INICIO, DATA_FIM, CHECK_IN, CHECK_OUT
)
SELECT q.QUARTO_ID, h.HOSPEDE_ID, f.FUNCIONARIO_ID, s.RESERVA_STATUS_ID,
       440.00,
       TIMESTAMP '2025-09-15 14:00:00', TIMESTAMP '2025-09-17 11:00:00',
       TIMESTAMP '2025-09-15 14:30:00', TIMESTAMP '2025-09-17 10:45:00'
FROM HTL_QUARTO q
JOIN HTL_HOSPEDE h ON h.NOME = 'Bruno Almeida'
JOIN HTL_FUNCIONARIO f ON f.EMAIL = 'joao.pereira@hotel.com'
JOIN HTL_RESERVA_STATUS s ON s.STATUS = 'FINALIZADO'
WHERE q.IDENTIFICADOR = '101';

-- 2) Fernanda no 201 (OCUPADO) 22–26/09
INSERT INTO HTL_RESERVA (
  QUARTO_ID, HOSPEDE_ID, CRIADO_POR, RESERVA_STATUS_ID,
  VALOR_CONTRATADO, DATA_INICIO, DATA_FIM, CHECK_IN, CHECK_OUT
)
SELECT q.QUARTO_ID, h.HOSPEDE_ID, f.FUNCIONARIO_ID, s.RESERVA_STATUS_ID,
       1400.00,
       TIMESTAMP '2025-09-22 14:00:00', TIMESTAMP '2025-09-26 11:00:00',
       TIMESTAMP '2025-09-22 15:00:00', NULL
FROM HTL_QUARTO q
JOIN HTL_HOSPEDE h ON h.NOME = 'Fernanda Costa'
JOIN HTL_FUNCIONARIO f ON f.EMAIL = 'maria.souza@hotel.com'
JOIN HTL_RESERVA_STATUS s ON s.STATUS = 'OCUPADO'
WHERE q.IDENTIFICADOR = '201';

-- 3) Pedro no 202 (AGUARDANDO CHECK-IN) 25–28/09
INSERT INTO HTL_RESERVA (
  QUARTO_ID, HOSPEDE_ID, CRIADO_POR, RESERVA_STATUS_ID,
  VALOR_CONTRATADO, DATA_INICIO, DATA_FIM, CHECK_IN, CHECK_OUT
)
SELECT q.QUARTO_ID, h.HOSPEDE_ID, f.FUNCIONARIO_ID, s.RESERVA_STATUS_ID,
       1050.00,
       TIMESTAMP '2025-09-25 14:00:00', TIMESTAMP '2025-09-28 11:00:00',
       NULL, NULL
FROM HTL_QUARTO q
JOIN HTL_HOSPEDE h ON h.NOME = 'Pedro Rocha'
JOIN HTL_FUNCIONARIO f ON f.EMAIL = 'ana.lima@hotel.com'
JOIN HTL_RESERVA_STATUS s ON s.STATUS = 'AGUARDANDO CHECK-IN'
WHERE q.IDENTIFICADOR = '202';

-- 4) Luiza no 301 (CANCELADO) 18–20/09
INSERT INTO HTL_RESERVA (
  QUARTO_ID, HOSPEDE_ID, CRIADO_POR, RESERVA_STATUS_ID,
  VALOR_CONTRATADO, DATA_INICIO, DATA_FIM, CHECK_IN, CHECK_OUT
)
SELECT q.QUARTO_ID, h.HOSPEDE_ID, f.FUNCIONARIO_ID, s.RESERVA_STATUS_ID,
       1000.00,
       TIMESTAMP '2025-09-18 14:00:00', TIMESTAMP '2025-09-20 11:00:00',
       NULL, NULL
FROM HTL_QUARTO q
JOIN HTL_HOSPEDE h ON h.NOME = 'Luiza Mendes'
JOIN HTL_FUNCIONARIO f ON f.EMAIL = 'joao.pereira@hotel.com'
JOIN HTL_RESERVA_STATUS s ON s.STATUS = 'CANCELADO'
WHERE q.IDENTIFICADOR = '301';

--------------------------------------------------------------------------------
-- HISTÓRICO DE STATUS (para cada reserva, step-by-step)
--------------------------------------------------------------------------------
-- Reserva Bruno/101: AGUARDANDO -> OCUPADO -> FINALIZADO
INSERT INTO HTL_RESERVA_STATUS_HIST (RESERVA_STATUS_ID, RESERVA_ID, STATUS_EM)
SELECT s.RESERVA_STATUS_ID, r.RESERVA_ID, TIMESTAMP '2025-09-15 10:00:00'
FROM HTL_RESERVA r
JOIN HTL_RESERVA_STATUS s ON s.STATUS = 'AGUARDANDO CHECK-IN'
JOIN HTL_QUARTO q ON q.QUARTO_ID = r.QUARTO_ID AND q.IDENTIFICADOR = '101'
JOIN HTL_HOSPEDE h ON h.HOSPEDE_ID = r.HOSPEDE_ID AND h.NOME = 'Bruno Almeida';

INSERT INTO HTL_RESERVA_STATUS_HIST (RESERVA_STATUS_ID, RESERVA_ID, STATUS_EM)
SELECT s.RESERVA_STATUS_ID, r.RESERVA_ID, TIMESTAMP '2025-09-15 14:30:00'
FROM HTL_RESERVA r
JOIN HTL_RESERVA_STATUS s ON s.STATUS = 'OCUPADO'
JOIN HTL_QUARTO q ON q.QUARTO_ID = r.QUARTO_ID AND q.IDENTIFICADOR = '101'
JOIN HTL_HOSPEDE h ON h.HOSPEDE_ID = r.HOSPEDE_ID AND h.NOME = 'Bruno Almeida';

INSERT INTO HTL_RESERVA_STATUS_HIST (RESERVA_STATUS_ID, RESERVA_ID, STATUS_EM)
SELECT s.RESERVA_STATUS_ID, r.RESERVA_ID, TIMESTAMP '2025-09-17 10:50:00'
FROM HTL_RESERVA r
JOIN HTL_RESERVA_STATUS s ON s.STATUS = 'FINALIZADO'
JOIN HTL_QUARTO q ON q.QUARTO_ID = r.QUARTO_ID AND q.IDENTIFICADOR = '101'
JOIN HTL_HOSPEDE h ON h.HOSPEDE_ID = r.HOSPEDE_ID AND h.NOME = 'Bruno Almeida';

-- Reserva Fernanda/201: AGUARDANDO -> OCUPADO
INSERT INTO HTL_RESERVA_STATUS_HIST (RESERVA_STATUS_ID, RESERVA_ID, STATUS_EM)
SELECT s.RESERVA_STATUS_ID, r.RESERVA_ID, TIMESTAMP '2025-09-22 11:00:00'
FROM HTL_RESERVA r
JOIN HTL_RESERVA_STATUS s ON s.STATUS = 'AGUARDANDO CHECK-IN'
JOIN HTL_QUARTO q ON q.QUARTO_ID = r.QUARTO_ID AND q.IDENTIFICADOR = '201'
JOIN HTL_HOSPEDE h ON h.HOSPEDE_ID = r.HOSPEDE_ID AND h.NOME = 'Fernanda Costa';

INSERT INTO HTL_RESERVA_STATUS_HIST (RESERVA_STATUS_ID, RESERVA_ID, STATUS_EM)
SELECT s.RESERVA_STATUS_ID, r.RESERVA_ID, TIMESTAMP '2025-09-22 15:00:00'
FROM HTL_RESERVA r
JOIN HTL_RESERVA_STATUS s ON s.STATUS = 'OCUPADO'
JOIN HTL_QUARTO q ON q.QUARTO_ID = r.QUARTO_ID AND q.IDENTIFICADOR = '201'
JOIN HTL_HOSPEDE h ON h.HOSPEDE_ID = r.HOSPEDE_ID AND h.NOME = 'Fernanda Costa';

-- Reserva Pedro/202: AGUARDANDO
INSERT INTO HTL_RESERVA_STATUS_HIST (RESERVA_STATUS_ID, RESERVA_ID, STATUS_EM)
SELECT s.RESERVA_STATUS_ID, r.RESERVA_ID, TIMESTAMP '2025-09-25 10:00:00'
FROM HTL_RESERVA r
JOIN HTL_RESERVA_STATUS s ON s.STATUS = 'AGUARDANDO CHECK-IN'
JOIN HTL_QUARTO q ON q.QUARTO_ID = r.QUARTO_ID AND q.IDENTIFICADOR = '202'
JOIN HTL_HOSPEDE h ON h.HOSPEDE_ID = r.HOSPEDE_ID AND h.NOME = 'Pedro Rocha';

-- Reserva Luiza/301: AGUARDANDO -> CANCELADO
INSERT INTO HTL_RESERVA_STATUS_HIST (RESERVA_STATUS_ID, RESERVA_ID, STATUS_EM)
SELECT s.RESERVA_STATUS_ID, r.RESERVA_ID, TIMESTAMP '2025-09-18 09:00:00'
FROM HTL_RESERVA r
JOIN HTL_RESERVA_STATUS s ON s.STATUS = 'AGUARDANDO CHECK-IN'
JOIN HTL_QUARTO q ON q.QUARTO_ID = r.QUARTO_ID AND q.IDENTIFICADOR = '301'
JOIN HTL_HOSPEDE h ON h.HOSPEDE_ID = r.HOSPEDE_ID AND h.NOME = 'Luiza Mendes';

INSERT INTO HTL_RESERVA_STATUS_HIST (RESERVA_STATUS_ID, RESERVA_ID, STATUS_EM)
SELECT s.RESERVA_STATUS_ID, r.RESERVA_ID, TIMESTAMP '2025-09-18 12:00:00'
FROM HTL_RESERVA r
JOIN HTL_RESERVA_STATUS s ON s.STATUS = 'CANCELADO'
JOIN HTL_QUARTO q ON q.QUARTO_ID = r.QUARTO_ID AND q.IDENTIFICADOR = '301'
JOIN HTL_HOSPEDE h ON h.HOSPEDE_ID = r.HOSPEDE_ID AND h.NOME = 'Luiza Mendes';

--------------------------------------------------------------------------------
-- SERVIÇOS POR RESERVA (usa VALOR do serviço no momento do lançamento)
--------------------------------------------------------------------------------
-- Bruno/101: Café da manhã, Lavanderia, Serviço de Quarto
INSERT INTO HTL_RESERVA_SERVICO (SERVICO_ID, RESERVA_ID, CONCLUIDO_EM, VALOR)
SELECT s.SERVICO_ID, r.RESERVA_ID, DATE '2025-09-16', s.VALOR
FROM HTL_SERVICO s
JOIN HTL_RESERVA r
  ON EXISTS (
       SELECT 1 FROM HTL_QUARTO q, HTL_HOSPEDE h
       WHERE q.QUARTO_ID = r.QUARTO_ID AND h.HOSPEDE_ID = r.HOSPEDE_ID
         AND q.IDENTIFICADOR = '101' AND h.NOME = 'Bruno Almeida'
     )
WHERE s.NOME = 'Café da manhã';

INSERT INTO HTL_RESERVA_SERVICO (SERVICO_ID, RESERVA_ID, CONCLUIDO_EM, VALOR)
SELECT s.SERVICO_ID, r.RESERVA_ID, DATE '2025-09-16', s.VALOR
FROM HTL_SERVICO s
JOIN HTL_RESERVA r
  ON EXISTS (
       SELECT 1 FROM HTL_QUARTO q, HTL_HOSPEDE h
       WHERE q.QUARTO_ID = r.QUARTO_ID AND h.HOSPEDE_ID = r.HOSPEDE_ID
         AND q.IDENTIFICADOR = '101' AND h.NOME = 'Bruno Almeida'
     )
WHERE s.NOME = 'Lavanderia';

INSERT INTO HTL_RESERVA_SERVICO (SERVICO_ID, RESERVA_ID, CONCLUIDO_EM, VALOR)
SELECT s.SERVICO_ID, r.RESERVA_ID, DATE '2025-09-16', s.VALOR
FROM HTL_SERVICO s
JOIN HTL_RESERVA r
  ON EXISTS (
       SELECT 1 FROM HTL_QUARTO q, HTL_HOSPEDE h
       WHERE q.QUARTO_ID = r.QUARTO_ID AND h.HOSPEDE_ID = r.HOSPEDE_ID
         AND q.IDENTIFICADOR = '101' AND h.NOME = 'Bruno Almeida'
     )
WHERE s.NOME = 'Serviço de Quarto';

-- Fernanda/201: Spa e Jantar
INSERT INTO HTL_RESERVA_SERVICO (SERVICO_ID, RESERVA_ID, CONCLUIDO_EM, VALOR)
SELECT s.SERVICO_ID, r.RESERVA_ID, DATE '2025-09-23', s.VALOR
FROM HTL_SERVICO s
JOIN HTL_RESERVA r
  ON EXISTS (
       SELECT 1 FROM HTL_QUARTO q, HTL_HOSPEDE h
       WHERE q.QUARTO_ID = r.QUARTO_ID AND h.HOSPEDE_ID = r.HOSPEDE_ID
         AND q.IDENTIFICADOR = '201' AND h.NOME = 'Fernanda Costa'
     )
WHERE s.NOME = 'Spa';

INSERT INTO HTL_RESERVA_SERVICO (SERVICO_ID, RESERVA_ID, CONCLUIDO_EM, VALOR)
SELECT s.SERVICO_ID, r.RESERVA_ID, DATE '2025-09-24', s.VALOR
FROM HTL_SERVICO s
JOIN HTL_RESERVA r
  ON EXISTS (
       SELECT 1 FROM HTL_QUARTO q, HTL_HOSPEDE h
       WHERE q.QUARTO_ID = r.QUARTO_ID AND h.HOSPEDE_ID = r.HOSPEDE_ID
         AND q.IDENTIFICADOR = '201' AND h.NOME = 'Fernanda Costa'
     )
WHERE s.NOME = 'Jantar';

